### ISSUE TITLE
can you please add Interstitial,Rewarded video,Native ads advanced and Native ads express? 

### ISSUE THREAD

**Issue by ghimireprashant** [numen31337/AKGADWrapper#1]
can you please add process to do all admob plugin .

**Comment by numen31337** [comment]
Hello @ghimireprashant, this is just a wrapper around a UIViewController to embed an AdMob banner. If you are looking for some complete solution for wrapping you advertisements nice and clean, I can suggest you look at some mobile mediation services such as Heyzap for example. Usually, they provide some nice wrappers around other Ads networks.

**Comment by ghimireprashant** [comment]
thank you for suggestion
